# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phoneSpecs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import getSpecs as gs

IMG = []
link = ""
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(480, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Data/UI_Icon/PhoneSearch.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.phoneImg = QtGui.QLabel(self.centralwidget)
        self.phoneImg.setGeometry(QtCore.QRect(10, 10, 111, 111))
        self.phoneImg.setText(_fromUtf8(""))
        global IMG
        IMG = gs.getPhoneName()
        self.phoneImg.setPixmap(QtGui.QPixmap(_fromUtf8("../Data/online/images/{}.jpg".format(IMG[1]))))
        self.phoneImg.setScaledContents(True)
        self.phoneImg.setObjectName(_fromUtf8("phoneImg"))
        self.phoneTitle = QtGui.QLabel(self.centralwidget)
        self.phoneTitle.setGeometry(QtCore.QRect(210, 20, 181, 21))
        self.phoneTitle.setObjectName(_fromUtf8("phoneTitle"))
        self.releasedStatic = QtGui.QLabel(self.centralwidget)
        self.releasedStatic.setGeometry(QtCore.QRect(110, 160, 81, 16))
        self.releasedStatic.setObjectName(_fromUtf8("releasedStatic"))
        self.releasedFigure = QtGui.QLabel(self.centralwidget)
        self.releasedFigure.setGeometry(QtCore.QRect(250, 160, 151, 16))
        self.releasedFigure.setObjectName(_fromUtf8("releasedFigure"))
        self.wgtStatic = QtGui.QLabel(self.centralwidget)
        self.wgtStatic.setGeometry(QtCore.QRect(110, 200, 61, 16))
        self.wgtStatic.setObjectName(_fromUtf8("wgtStatic"))
        self.wgtFigure = QtGui.QLabel(self.centralwidget)
        self.wgtFigure.setGeometry(QtCore.QRect(250, 200, 141, 16))
        self.wgtFigure.setObjectName(_fromUtf8("wgtFigure"))
        self.osStatic = QtGui.QLabel(self.centralwidget)
        self.osStatic.setGeometry(QtCore.QRect(110, 240, 47, 13))
        self.osStatic.setObjectName(_fromUtf8("osStatic"))
        self.osName = QtGui.QLabel(self.centralwidget)
        self.osName.setGeometry(QtCore.QRect(250, 240, 171, 16))
        self.osName.setObjectName(_fromUtf8("osName"))
        self.storageStatic = QtGui.QLabel(self.centralwidget)
        self.storageStatic.setGeometry(QtCore.QRect(110, 280, 47, 20))
        self.storageStatic.setObjectName(_fromUtf8("storageStatic"))
        self.storageFigure = QtGui.QLabel(self.centralwidget)
        self.storageFigure.setGeometry(QtCore.QRect(250, 280, 191, 16))
        self.storageFigure.setObjectName(_fromUtf8("storageFigure"))
        self.displayStatic = QtGui.QLabel(self.centralwidget)
        self.displayStatic.setGeometry(QtCore.QRect(110, 330, 47, 13))
        self.displayStatic.setObjectName(_fromUtf8("displayStatic"))
        self.cameraStatic = QtGui.QLabel(self.centralwidget)
        self.cameraStatic.setGeometry(QtCore.QRect(110, 370, 47, 13))
        self.cameraStatic.setObjectName(_fromUtf8("cameraStatic"))
        self.ramStatic = QtGui.QLabel(self.centralwidget)
        self.ramStatic.setGeometry(QtCore.QRect(110, 410, 81, 16))
        self.ramStatic.setObjectName(_fromUtf8("ramStatic"))
        self.batteryStatic = QtGui.QLabel(self.centralwidget)
        self.batteryStatic.setGeometry(QtCore.QRect(110, 450, 47, 13))
        self.batteryStatic.setObjectName(_fromUtf8("batteryStatic"))
        self.displayFigure = QtGui.QLabel(self.centralwidget)
        self.displayFigure.setGeometry(QtCore.QRect(250, 330, 181, 16))
        self.displayFigure.setObjectName(_fromUtf8("displayFigure"))
        self.cameraFigure = QtGui.QLabel(self.centralwidget)
        self.cameraFigure.setGeometry(QtCore.QRect(250, 370, 171, 16))
        self.cameraFigure.setObjectName(_fromUtf8("cameraFigure"))
        self.ramFigure = QtGui.QLabel(self.centralwidget)
        self.ramFigure.setGeometry(QtCore.QRect(250, 410, 201, 16))
        self.ramFigure.setObjectName(_fromUtf8("ramFigure"))
        self.batteryFigure = QtGui.QLabel(self.centralwidget)
        self.batteryFigure.setGeometry(QtCore.QRect(250, 450, 211, 16))
        self.batteryFigure.setObjectName(_fromUtf8("batteryFigure"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(133, 10, 20, 141))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 461, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.searchStatic = QtGui.QLabel(self.centralwidget)
        self.searchStatic.setGeometry(QtCore.QRect(160, 90, 47, 13))
        self.searchStatic.setObjectName(_fromUtf8("searchStatic"))
        self.searchFigures = QtGui.QLabel(self.centralwidget)
        self.searchFigures.setGeometry(QtCore.QRect(230, 90, 81, 13))
        self.searchFigures.setObjectName(_fromUtf8("searchFigures"))
        self.likeStatic = QtGui.QLabel(self.centralwidget)
        self.likeStatic.setGeometry(QtCore.QRect(330, 90, 47, 13))
        self.likeStatic.setObjectName(_fromUtf8("likeStatic"))
        self.likeFigure = QtGui.QLabel(self.centralwidget)
        self.likeFigure.setGeometry(QtCore.QRect(390, 90, 71, 13))
        self.likeFigure.setObjectName(_fromUtf8("likeFigure"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(120, 180, 171, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(120, 220, 171, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(120, 260, 171, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(120, 300, 171, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(120, 350, 171, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(120, 390, 171, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(120, 430, 171, 20))
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(80, 480, 261, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.knowMore = QtGui.QLabel(self.centralwidget)
        self.knowMore.setGeometry(QtCore.QRect(370, 480, 101, 20))
        self.knowMore.setObjectName(_fromUtf8("knowMore"))
        self.searchPer = QtGui.QLabel(self.centralwidget)
        self.searchPer.setGeometry(QtCore.QRect(260, 120, 151, 20))
        self.searchPer.setObjectName(_fromUtf8("searchPer"))
        self.popylarity = QtGui.QLabel(self.centralwidget)
        self.popylarity.setGeometry(QtCore.QRect(160, 120, 61, 16))
        self.popylarity.setObjectName(_fromUtf8("popylarity"))
        self.line_11 = QtGui.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(310, 60, 3, 61))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        QtCore.QObject.connect(self.knowMore, QtCore.SIGNAL(_fromUtf8("linkActivated(QString)")), self.openLink)
    def openLink(self):
        import webbrowser
        global link

        webbrowser.open(link, new=0, autoraise=True)
    def retranslateUi(self, MainWindow):
        details = gs.getSpec()
        MainWindow.setWindowTitle(_translate("MainWindow", IMG[0], None))
        self.phoneTitle.setText(_translate("MainWindow", IMG[0] , None))
        self.releasedStatic.setText(_translate("MainWindow", "Released On", None))
        self.releasedFigure.setText(_translate("MainWindow", details[0], None))
        self.wgtStatic.setText(_translate("MainWindow", "Weight", None))
        self.wgtFigure.setText(_translate("MainWindow", details[1], None))
        self.osStatic.setText(_translate("MainWindow", "OS", None))
        self.osName.setText(_translate("MainWindow", details[2], None))
        self.storageStatic.setText(_translate("MainWindow", "Storage", None))
        self.storageFigure.setText(_translate("MainWindow",details[3] , None))
        self.displayStatic.setText(_translate("MainWindow", "Display", None))
        self.cameraStatic.setText(_translate("MainWindow", "Camera", None))
        self.ramStatic.setText(_translate("MainWindow", "RAM/Processor", None))
        self.batteryStatic.setText(_translate("MainWindow", "Battery", None))
        self.displayFigure.setText(_translate("MainWindow", details[4], None))
        self.cameraFigure.setText(_translate("MainWindow", details[5], None))
        self.ramFigure.setText(_translate("MainWindow", details[6], None))
        self.batteryFigure.setText(_translate("MainWindow", details[7], None))
        self.searchStatic.setText(_translate("MainWindow", "Searches", None))
        self.searchFigures.setText(_translate("MainWindow", details[8], None))
        self.likeStatic.setText(_translate("MainWindow", "Likes", None))
        self.likeFigure.setText(_translate("MainWindow", details[10], None))
        self.knowMore.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a href=\"{}\"><span style=\" text-decoration: underline; color:#0000ff;\">Know More</span></a></p></body></html>".format(details[11]), None))
        self.searchPer.setText(_translate("MainWindow", details[9], None))
        self.popylarity.setText(_translate("MainWindow", "Popularity", None))
        global link
        link = details[11]
